package com.example.momentra.ui.shell.maestro

/**
 * Stable Maestro / TalkBack accessibility IDs (S9-QA).
 * Keep in sync with `.maestro/shared/accessibility-ids.md` and iOS identifiers.
 */
object MaestroIds {
    const val LOGIN_SCREEN = "login.screen"
    const val LOGIN_EMAIL = "login.email"
    const val LOGIN_PASSWORD = "login.password"
    const val LOGIN_SUBMIT = "login.submit"
    const val LOGIN_GOOGLE = "login.google"
    const val LOGIN_APPLE = "login.apple"
    const val LOGIN_FORGOT = "login.forgot"
    const val LOGIN_ERROR = "login.error"

    const val ONBOARDING_SKIP = "onboarding.skip"
    const val CONSENT_GATE = "consent.gate"
    const val CONSENT_CONTINUE = "consent.continue"

    const val TOPBAR = "topbar.root"
    const val TOPBAR_QR = "topbar.qr"
    const val TOPBAR_LIFE360 = "topbar.life360"
    const val TOPBAR_NEW_MOMENT = "topbar.new_moment"
    const val TOPBAR_REFER = "topbar.refer"
    const val TOPBAR_PROFILE = "topbar.profile"

    const val CONTEXT_SWITCHER = "context.switcher"
    const val CONTEXT_PERSONAL = "context.personal"
    const val CONTEXT_GROUP = "context.group"
    const val CONTEXT_BUSINESS = "context.business"
    const val CONTEXT_CIRCLE = "context.circle"

    const val MOMENT_SWITCHER = "moment.switcher"
    const val MOMENT_SWITCHER_INVITE = "moment.switcher.invite"
    const val MOMENT_CREATE = "moment.create"
    const val COMPANY_SWITCHER = "company.switcher"

    const val BOTTOM_NAV = "bottom.nav"
    const val BOTTOM_PULSE = "bottom.pulse"
    const val BOTTOM_MOMENTS = "bottom.moments"
    const val BOTTOM_QUICKADD = "bottom.quickadd"
    const val BOTTOM_LIFE = "bottom.life"
    const val BOTTOM_MEMORY = "bottom.memory"

    const val PERSONAL_EXPENSE_AMOUNT = "personal.expense.amount"
    const val PERSONAL_EXPENSE_CATEGORY = "personal.expense.category"
    const val PERSONAL_EXPENSE_ACCOUNT = "personal.expense.account"
    const val PERSONAL_EXPENSE_DATE = "personal.expense.date"
    const val PERSONAL_EXPENSE_MORE = "personal.expense.more"
    const val PERSONAL_EXPENSE_NOTE = "personal.expense.note"
    const val PERSONAL_EXPENSE_SUBMIT = "personal.expense.submit"

    const val PERSONAL_LIFEOPS_RECOVERY_NOTE = "personal.lifeops.recovery.note"
    const val PERSONAL_LIFEOPS_RECOVERY_SUBMIT = "personal.lifeops.recovery.submit"
    const val PERSONAL_LIFEOPS_MOOD_NOTE = "personal.lifeops.mood.note"
    const val PERSONAL_LIFEOPS_MOOD_SUBMIT = "personal.lifeops.mood.submit"
    const val PERSONAL_LIFEOPS_ATTENTION_NOTE = "personal.lifeops.attention.note"
    const val PERSONAL_LIFEOPS_ATTENTION_SUBMIT = "personal.lifeops.attention.submit"
    const val PERSONAL_LIFEOPS_ADJUST_NOTE = "personal.lifeops.adjust.note"
    const val PERSONAL_LIFEOPS_ADJUST_SUBMIT = "personal.lifeops.adjust.submit"

    const val PERSONAL_INCOME_AMOUNT = "personal.income.amount"
    const val PERSONAL_INCOME_CATEGORY = "personal.income.category"
    const val PERSONAL_INCOME_SUBCATEGORY = "personal.income.subcategory"
    const val PERSONAL_INCOME_ACCOUNT = "personal.income.account"
    const val PERSONAL_INCOME_NOTE = "personal.income.note"
    const val PERSONAL_INCOME_SUBMIT = "personal.income.submit"

    const val PERSONAL_MONEY_TRANSFER_NOTE = "personal.money.transfer.note"
    const val PERSONAL_MONEY_TRANSFER_AMOUNT = "personal.money.transfer.amount"
    const val PERSONAL_MONEY_TRANSFER_SUBMIT = "personal.money.transfer.submit"
    const val PERSONAL_MONEY_SAVINGS_AMOUNT = "personal.money.savings.amount"
    const val PERSONAL_MONEY_SAVINGS_ACCOUNT = "personal.money.savings.account"
    const val PERSONAL_MONEY_SAVINGS_SUBMIT = "personal.money.savings.submit"
    const val PERSONAL_MONEY_ADD_ACCOUNT = "personal.money.add_account"

    const val PERSONAL_ACCOUNT_PICKER = "personal.account.picker"
    const val PERSONAL_ACCOUNT_PICKER_CLOSE = "personal.account.picker.close"
    const val PERSONAL_ACCOUNT_PICKER_CREATE = "personal.account.picker.create"
    const val PERSONAL_ACCOUNT_ADD_NAME = "personal.account.add.name"
    const val PERSONAL_ACCOUNT_ADD_SUBMIT = "personal.account.add.submit"
    const val PERSONAL_ACCOUNT_ADD_TYPE_BANK = "personal.account.add.type.bank"
    const val PERSONAL_ACCOUNT_ADD_TYPE_CASH = "personal.account.add.type.cash"
    const val PERSONAL_ACCOUNT_ADD_TYPE_CREDIT = "personal.account.add.type.credit"

    const val GROUP_EXPENSE_AMOUNT = "group.expense.amount"
    const val GROUP_EXPENSE_PAYER = "group.expense.payer"
    const val GROUP_EXPENSE_SPLIT = "group.expense.split"
    const val GROUP_EXPENSE_SPLIT_EQUAL = "group.expense.split.equal"
    const val GROUP_EXPENSE_SPLIT_PERCENTAGE = "group.expense.split.percentage"
    const val GROUP_EXPENSE_SPLIT_EXACT = "group.expense.split.exact"
    const val GROUP_EXPENSE_SPLIT_SHARES = "group.expense.split.shares"
    const val GROUP_EXPENSE_SPLIT_VALUE = "group.expense.split.value"
    const val GROUP_EXPENSE_NOTE = "group.expense.note"
    const val GROUP_EXPENSE_SUBMIT = "group.expense.submit"

    fun groupExpenseSplitStrategy(strategy: String): String =
        "group.expense.split.${strategy.lowercase()}"

    const val GROUP_INVITE_CREATE = "group.invite.create"
    const val GROUP_INVITE_CODE = "group.invite.code"
    const val GROUP_INVITE_REDEEM = "group.invite.redeem"

    const val BUSINESS_EXPENSE_AMOUNT = "business.expense.amount"
    const val BUSINESS_EXPENSE_CATEGORY = "business.expense.category"
    const val BUSINESS_EXPENSE_NOTE = "business.expense.note"
    const val BUSINESS_EXPENSE_SUBMIT = "business.expense.submit"

    const val BUSINESS_REVENUE_AMOUNT = "business.revenue.amount"
    const val BUSINESS_REVENUE_SUBMIT = "business.revenue.submit"

    const val BUSINESS_INVOICE_CUSTOMER = "business.invoice.customer"
    const val BUSINESS_INVOICE_AMOUNT = "business.invoice.amount"
    const val BUSINESS_INVOICE_LINE_ADD = "business.invoice.line.add"
    const val BUSINESS_INVOICE_SUBMIT = "business.invoice.submit"

    const val BUSINESS_APPROVAL_APPROVE = "business.approval.approve"
    const val BUSINESS_APPROVAL_REJECT = "business.approval.reject"

    const val ACCOUNT_SIGN_OUT = "account.sign_out"
    const val LIFE360_COMING_SOON = "life360.coming_soon"
    const val CIRCLE_COMING_SOON = "circle.coming_soon"

    // --- Master Certification (Q0+) Quick Add tiles ---
    const val QA_TILE_INCOME = "qa.tile.income"
    const val QA_TILE_EXPENSE = "qa.tile.expense"
    const val QA_TILE_RECOVERY = "qa.tile.recovery"
    const val QA_TILE_MOOD = "qa.tile.mood"
    const val QA_TILE_ATTENTION = "qa.tile.attention"
    const val QA_TILE_ADJUST = "qa.tile.adjust"
    const val QA_TILE_MILESTONE = "qa.tile.milestone"
    const val QA_TILE_OPPORTUNITY = "qa.tile.opportunity"
    const val QA_TILE_PIVOT = "qa.tile.pivot"
    const val QA_TILE_PROGRESS = "qa.tile.progress"
    const val QA_TILE_LEARNING = "qa.tile.learning"
    const val QA_TILE_EXPERIENCE = "qa.tile.experience"
    const val QA_TILE_WELLBEING = "qa.tile.wellbeing"
    const val QA_TILE_DISCOVERY = "qa.tile.discovery"
    const val QA_TILE_EXPRESSION = "qa.tile.expression"
    const val QA_TILE_CONNECTION = "qa.tile.connection"
    const val QA_TILE_SUPPORT = "qa.tile.support"
    const val QA_TILE_SHARED_EXP = "qa.tile.shared_exp"
    const val QA_TILE_INVESTMENT = "qa.tile.investment"
    const val QA_TILE_TRANSFER = "qa.tile.transfer"
    const val QA_TILE_SAVINGS = "qa.tile.savings"
    const val QA_TILE_CONTRIBUTE = "qa.tile.contribute"
    const val QA_TILE_SETTLE = "qa.tile.settle"
    const val QA_TILE_PEOPLE = "qa.tile.people"
    const val QA_TILE_BUDGET = "qa.tile.budget"
    const val QA_SEARCH = "qa.search"
    const val PULSE_PROGRESS = "pulse.progress"
    const val PULSE_PROGRESS_BUDGET = "pulse.progress.budget"
    const val QA_TILE_REVENUE = "qa.tile.revenue"
    const val QA_TILE_INVOICE = "qa.tile.invoice"

    const val PERSONAL_SETUP_LIFE_OPS = "personal.setup.life_operations"
    const val PERSONAL_SETUP_FUTURE = "personal.setup.future_building"
    const val PERSONAL_SETUP_LIFESTYLE = "personal.setup.lifestyle"
    const val PERSONAL_SETUP_RELATIONSHIPS = "personal.setup.relationships"
    const val PERSONAL_SETUP_SUBMIT = "personal.setup.submit"

    const val GROUP_SETUP_TYPE_PREFIX = "group.setup.type."
    const val GROUP_SETUP_SUBMIT = "group.setup.submit"

    const val BUSINESS_SETUP_TEAM = "business.setup.team_operations"
    const val BUSINESS_SETUP_RUNWAY = "business.setup.business_runway"
    const val BUSINESS_SETUP_OPS = "business.setup.business_operations"
    const val BUSINESS_SETUP_SUBMIT = "business.setup.submit"
    const val BUSINESS_COMPANY_CREATE = "business.company.create"
    const val BUSINESS_COMPANY_SUBMIT = "business.company.submit"

    const val SETUP_TITLE = "setup.title"
    const val SETUP_DROPDOWN = "setup.dropdown"

    fun setupDate(key: String) = "setup.date.$key"
    fun setupDateTime(key: String) = "setup.datetime.$key"
    fun setupTime(key: String) = "setup.time.$key"
    fun setupDropdown(key: String) = "setup.dropdown.$key"
    fun setupField(key: String) = "setup.field.$key"
}
