import Foundation

enum AnalyticsScreens {
    static let splash = "screen_splash"
    static let sessionRestore = "screen_session_restore"
    static let onboarding = "screen_onboarding"
    static let onboardingScene1 = "screen_onboarding_scene_1"
    static let onboardingScene2 = "screen_onboarding_scene_2"
    static let onboardingScene3 = "screen_onboarding_scene_3"
    static let onboardingProduct1 = "screen_onboarding_product_1"
    static let onboardingProduct2 = "screen_onboarding_product_2"
    static let onboardingProduct3 = "screen_onboarding_product_3"
    static let login = "screen_login"
    static let loginSignIn = "screen_login_sign_in"
    static let loginRegister = "screen_login_register"
    static let loginPhone = "screen_login_phone"
    static let home = "screen_home"
    static let personalCreate = "screen_personal_create"
    static let personalSetupLifeOps = "screen_personal_setup_life_ops"
    static let personalSetupFuture = "screen_personal_setup_future"
    static let personalSetupLifestyle = "screen_personal_setup_lifestyle"
    static let personalSetupRelationships = "screen_personal_setup_relationships"
    static let companySetup = "screen_company_setup"
    static let businessCreate = "screen_business_create"
    static let businessSetupTeamOps = "screen_business_setup_team_ops"
    static let businessSetupRunway = "screen_business_setup_runway"
    static let businessSetupOps = "screen_business_setup_ops"
}

enum AnalyticsWidgets {
    static let onboardingSkip = "onboarding/btn_skip"
    static let onboardingStepInside = "onboarding/btn_step_inside"
    static let onboardingNext = "onboarding/btn_next"
    static let onboardingGetStarted = "onboarding/btn_get_started"
    static let loginTabSignIn = "login/tab_sign_in"
    static let loginTabRegister = "login/tab_register"
    static let loginTabPhone = "login/tab_phone"
    static let loginBtnEmailSubmit = "login/btn_email_submit"
    static let loginBtnPhoneSend = "login/btn_phone_send_sms"
    static let loginBtnPhoneVerify = "login/btn_phone_verify"
    static let loginBtnPhoneChange = "login/btn_phone_change_number"
    static let loginBtnGoogle = "login/btn_google"
    static let loginBtnApple = "login/btn_apple"
    static let splashComplete = "splash/event_complete"
}
